### ISSUE TITLE
Workflow for the Unsupervised ancient DNA damage

### ISSUE THREAD

**Issue by kkdey** [halasadi/ancient-damage#23]
To do : 

1. Sherpa data (moderns +ancients) from David.  See if we see the T->AAA patterns in that data as well. Also whether we can separate the moderns and ancients.

2. Download modern BAM files from 1000 genomes project. Fit the model to those BAM files and see if they differ from Lindo's moderns data. If they do, we have another example of lab effect. Also we look for the T->AAA patterns in the modern data. (I think this is the first thing we should do, as I would be busy till 9th of Dec, so the analysis part might take time)

3. Do an enrichment analysis of the patterns we see in moderns vs the ones that appear in ancient samples.

4. Fit a (mutation, bin) unsupervised  model on Anna Gosling's data. We say that the flanking bases information was not important in the full (mutation, bin, flanking base) features and so opted for this reduced model. Do the clustering based on that.

5. Once we are happy that T->AAA is a recurring trend in some samples, we seek to understand what is going on with these?

6. We also try to build a better story with the lab effects issue as that seems to be an important deal. 

7. We improve the visualization by adding the bin information with the logo plot. Plus, conditional logo plots.

8. We modify the CountClust model to incorporate the independence structure and refit the data and see if we get anything better than what we already have.

9. Once all these things are taken care of, we start writing the paper and build the software.

**Comment by halasadi** [comment]
How can we do the conditional log plots with the independence model?
